### ISSUE TITLE
TypeError in log everytime I open a C++-file

### ISSUE THREAD

**Issue by AndersHogqvist** [jbenden/vscode-c-cpp-flylint#142]
The extension actually seems to work as expected but I've noticed that there's a TypeError in the log every time I open a C++-file:

```
onDidOpen starting analysis.
Incoming request for isTrusted property. Have true.
TypeError: Patterns must be a string (non empty) or an array of strings
  at f (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:53083)
  at AsyncFunction.e.sync (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:53195)
  at .../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:18685
  at _t (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:101604)
  at Function._s (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:136405)
  at D (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:18614)
  at .../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:20564
  at .../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:20615
  at .../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:21255
  at async L (.../jbenden.c-cpp-flylint-1.10.2/server/out/server.js:2:20388)
Performing lint scan of file.h
Completed lint scans...
Skipping analysis because ON_SAVE !== ON_TYPE.
```

In my user settings I have only cppcheck enabled (v. 2.2), flawfinder, flexelint, lizard and clang are all disabled. And wrote in the beginning I get the cppcheck analysis when I'm working in my code but I thought I'd report this anyway since there's obviously something going on in the background that doesn't add up.

**Comment by jbenden** [comment]
Hello,

A new extension was just published a minute ago. If you still experience this problem, then please capture a full debugging log and post it here. In the extension's settings you may enable `debug` and `verbose`.

Thanks,
-Joe

**Comment by AndersHogqvist** [comment]
Thank you! I will give it a try but it's not possible to upload any logs here I'm afraid. The development environment is off grid so to speak.

**Comment by AndersHogqvist** [comment]
Still getting the error. I did enable verbose debugging and even though I can't transfer the log file and post it here I can write the important stuff manually:

```
onDidOpen starting analysis.
Incoming request for isTrusted property. Have true.
Proxying request for activeConfigName
Sending request to "ms-vstools.cpptools" extension.
TypeError: Petterns must be a string (non empty) or an array of strings
  at f (......./server/out/server.js:2:55342)
  at AsyncFunction.e.sync (......./server/out/server.js:2:55454)
  at ......./server/out/server.js:2:19926
  at _t (......./server/out/server.js:2:103863)
  at Function._s (......./server/out/server.js:2:138664)
  at N (......./server/out/server.js:2:19855)
  at async q (......./server/out/server.js:2:21671)
Path: ${workspaceFolder} VALUE: .... Globbed is: ....
Adding path: ....
Path: ${workspaceFolder}/build/..... VALUE: ..... Globbed is: .....
Adding path: .....
xxxx.cpp force = false.
xxxx.cpp is now at version number 1.
Performing ling scan of xxxx.cpp...
executing: clang -fsyntax-only -fno-color-diagnostics -fno-caret-diagnostics -fno-diagnostics-show-option -fdiagnostics-show-category=name -ferror-limit=2++ --std=c++14 -fblocks -Wall -Wextra -Dxxxx -I ....
[ '' ]
[
  'a lot of semantic issues etc'
]
Clang exited with status code 1
```

So as you can see it's actually checking the opened file (here called xxxx.cpp) and reports the issues that it finds, so it doesn't seem like the error is affecting the functionality.

**Comment by jbenden** [comment]
Would you mind posting your config?, as I am not really sure where this error stems from (and the locations shown are from transpilation and thus not useful.)

Thanks,
-Joe

**Comment by evanperrygrove** [comment]
I am also getting this error, but in a C codebase rather than C++. There are a whole bunch of log messages right before the exception that look a little odd:

```
Path: ${workspaceFolder}/example/foo  VALUE: c:\Users\Evan\Documents\project/example/foo  Globbed is: 
Path: ${workspaceFolder}/example/bar  VALUE: c:\Users\Evan\Projects\project/example/bar  Globbed is: 
Path: ${workspaceFolder}/example/bat  VALUE: c:\Users\Evan\Projects\project/example/bat  Globbed is: 
Path: ${workspaceFolder}/example/baz  VALUE: c:\Users\Evan\Projects\project/example/baz  Globbed is: 
...
TypeError: Patterns must be a string (non empty) or an array of strings
```

I'm assuming there is supposed to be some text following the words "Globbed is."

Could this have something to do with the Windows path separators?

**Comment by evanperrygrove** [comment]
Update: I just realized something that may be helpful. The very last `Path: ${workspaceFolder}/...` log message occurs right before the code would get to this entry in my c_cpp_properties.json:
```
   "${default}"
```
