### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by Samega7Cattac** [jbenden/vscode-c-cpp-flylint#157]
```
Could not find or parse the workspace c_cpp_properties.json file; continuing...
TypeError: Cannot read properties of undefined (reading 'length')
    at N (/home/user/.vscode/extensions/jbenden.c-cpp-flylint-1.11.0/server/out/server.js:2:20885)
    at async q (/home/user/.vscode/extensions/jbenden.c-cpp-flylint-1.11.0/server/out/server.js:2:21671)
<path>/ProjectTree.cpp force = false.
<path>/ProjectTree.cpp is now at version number 1.
Performing lint scan of <path>/ProjectTree.cpp...
executing:  /usr/bin/cppcheck --inline-suppr --enable=warning,style,performance,portability,information -I <path>//include -I /<path>/include/libondas -I <path>/include/libmoda -I /<path>/libsurf -I /<path>/source -I /<path>/common -I /home/oncontrol/projects/databridge/<path>/server -I /<path>/gui -I /<path>/serverui -I /usr/include/glibmm-2.68 -I /usr/lib/glibmm-2.68/include -I /usr/include/glib-2.0 -I /usr/lib/glib-2.0/include -I /usr/include/gtkmm-4.0 -I /usr/lib/gtkmm-4.0/include -I /usr/include/sigc++-3.0 -I /usr/lib/sigc++-3.0/include -I /usr/lib/pangomm-2.48/include -I /usr/include/pangomm-2.48 -I /usr/include/pango-1.0 -I /usr/include/harfbuzz -I /usr/include/giomm-2.68 -I /usr/lib/giomm-2.68/include -I /usr/include/cairomm-1.16 -I /usr/lib/cairomm-1.16/include -I /usr/include/cairo -I /usr/include/freetype2 -I /usr/include/gtk-4.0 -I /usr/include/gdk-pixbuf-2.0 -I /usr/include/graphene-1.0 -I /usr/lib/graphene-1.0/include -I /usr/include/botan-2 --std=c11 --std=c++11 --language=c++ --platform=native --template="{file}  {line}  {severity} {id}: {message}" --force /<path>/ProjectTree.cpp
[
  'Checking <path>/ProjectTree.cpp ...',
  ''
]
[
  '"<path>/ProjectTree.cpp  0  information noValidConfiguration: This file is not analyzed. Cppcheck failed to extract a valid configuration. Use -v for more details."',
  '"nofile  0  information missingIncludeSystem: Cppcheck cannot find all the include files (use --check-config for details)"',
  ''
]
Completed lint scans...
Skipping analysis because ON_SAVE !== ON_TYPE.
```
`<path>` is just to redact the complete path

**Comment by dzidaV8** [comment]
Was there any progress on this issue? For me it happens when c_cpp_properties.json file is present

**Comment by Samega7Cattac** [comment]
I have other issues happening so I can't isolate this one.
And kinda gave up.
