### ISSUE TITLE
Line could not be parsed: void f(int x)

### ISSUE THREAD

**Issue by GioCC** [jbenden/vscode-c-cpp-flylint#187]
VS Code 1.74.3, GCC (g++) 12.2.0, Extension 1.13.0 and Clang 14.0
```
'Line could not be parsed: void f(int x)' while validating: c:\Progetti\Firmware\undisclosed_path\Undisclosed_File.cpp. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: void f(int x)
    at c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:12688
    at Array.forEach (<anonymous>)
    at a.parseLines (c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:12437)
    at a.lint (c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:12340)
    at c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:21824
    at Array.forEach (<anonymous>)
    at B (c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:21799)
    at async c:\Users\Xxxxx\.vscode\extensions\jbenden.c-cpp-flylint-1.13.0\server\out\server.js:2:24716
```
I would be happy to supply the actual offending file by PM (not publicly).
I can see no line indication to help spot the error by myself.

**Comment by troyliu0105** [comment]
@GioCC hallo GioCC, I (may) found the solution. Did you turn the option 'c-cpp-flylint.cppcheck.verbose' on? u should try turn it off.
cuz the error msg 'void f(int x)...balabala' is from cppcheck verbose output. like below:
![图片](https://github.com/jbenden/vscode-c-cpp-flylint/assets/5518286/ad78a1d9-5cd5-448c-b3d3-93863d21ca4b)
