### ISSUE TITLE
Line could not be parsed: cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16

### ISSUE THREAD

**Issue by FabianGa** [jbenden/vscode-c-cpp-flylint#196]
Hi,

I get this error during every cppcheck scan:

```
'Line could not be parsed: cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16. Please enable it explicitly if you require it.' while validating: XX. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16. Please enable it explicitly if you require it.
    at .vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12688
    at Array.forEach (<anonymous>)
    at a.parseLines (.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12437)
    at a.lint (.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12340)
    at /vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:21824
    at Array.forEach (<anonymous>)
    at B (.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:21799)
    at async .vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:24716
```

There is no more information in the output console, as referred to.

thanks

**Comment by LeChatP** [comment]
Same here, This is annoying and sometimes goes into a VSCode crash if I would click on the "configure notification" button.

**Comment by whois-hoeless** [comment]
It seems like the owner of cppcheck warns people of what will happen in the next release before even releasing it. To me it looks like he prints that error but also (still) enables missingInclude. I would've warned people with the actual release instead.. Not too sure if you can fix that warning, I will comment again if I find it, otherwise I will disable cppcheck temporarily

**Comment by joe733** [comment]
Thanks for the extension. I have the same error.

```js
"Line could not be parsed: cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16. Please enable it explicitly if you require it." while validating: /home/us-er/Documents/workspace/github/rubric/c/searchLinear.c. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16. Please enable it explicitly if you require it.
    at /home/us-er/.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12688
    at Array.forEach (<anonymous>)
    at a.parseLines (/home/us-er/.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12437)
    at a.lint (/home/us-er/.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:12340)
    at /home/us-er/.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:21824
    at Array.forEach (<anonymous>)
    at Function.B (/home/us-er/.vscode/extensions/jbenden.c-cpp-flylint-1.13.0/server/out/server.js:2:21799)
```

Last release was on Jan 7, and fix was on Jun 26, when can we expect next release please?

**Comment by jbenden** [comment]
It just published! https://github.com/jbenden/vscode-c-cpp-flylint/releases/tag/v1.13.1
