### ISSUE TITLE
fails to parse output from cppcheck 2.12

### ISSUE THREAD

**Issue by lachlanc** [jbenden/vscode-c-cpp-flylint#208]
add-on fails to parse output from cppcheck 2.12, rolling back to 2.8 solves issues outputted text is slightly different, add-on also fails to show correctly parsed lines 
bellow is a truncated output comparing 2.12 (TOP) vs 2.8 

`PS C:\Projects\Proj\src> C:\Program Files\Cppcheck\cppcheck.exe --inline-suppr --enable=warning,style,performance,portability,information --std=c99 --platform=unix32 --template="{file}  {line}  {severity} {id}: {message}" --force --inconclusive c:/Projects/Proj/src/share_lib/sourcefile.c
cppcheck: '--enable=information' will no longer implicitly enable 'missingInclude' starting with 2.16. Please enable it explicitly if you require it.
Checking c:\Projects\Proj\src\share_lib\sourcefile.c ...
c:\Projects\Proj\src\share_lib\sourcefile.c  241  style badBitmaskCheck: Operator '|' with one operand equal to zero is redundant.
c:\Projects\Proj\src\share_lib\sourcefile.c  1055  style badBitmaskCheck: Operator '|' with one operand equal to zero is redundant.

Active checkers: 114/565
`

PS C:\Projects\Proj\src> C:\Program Files\Cppcheck\cppcheck.exe --inline-suppr --enable=warning,style,performance,portability,information --std=c99 --platform=unix32 --template="{file}  {line}  {severity} {id}: {message}" --force --inconclusive c:/Projects/Proj/src/share_lib/sourcefile.c
Checking c:\Projects\Proj\src\share_lib\sourcefile.c ...
c:\Projects\Proj\src\share_lib\sourcefile.c  241  style duplicateExpression: Same expression '0' found multiple times in chain of '|' operators.
c:\Projects\Proj\src\share_lib\sourcefile.c  1055  error integerOverflow: Signed integer overflow for expression '0x2<<30'.
nofile  0  information missingInclude: Cppcheck cannot find all the include files (use --check-config for details)
PS C:\Projects\Proj\src>

error message from popup 

Line could not be parsed: Active checkers: 114/565' while validating: c:\Projects\Proj\src\share_lib\sourcefile.c. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: Active checkers: 114/565
    at c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:12689
    at Array.forEach (<anonymous>)
    at a.parseLines (c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:12438)
    at a.lint (c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:12341)
    at c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:21825
    at Array.forEach (<anonymous>)
    at B (c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:21800)
    at async c:\Users\lachlan\.vscode\extensions\jbenden.c-cpp-flylint-1.13.1\server\out\server.js:2:24848

**Comment by lachlanc** [comment]
looks like this is fixed with #204
