### ISSUE TITLE
Line could not be parsed: Active checkers: 161/565' while validating ....

### ISSUE THREAD

**Issue by iustusae** [jbenden/vscode-c-cpp-flylint#209]
``` txt
'Line could not be parsed: Active checkers: 161/565' while validating: /Users/iustus/lcpp/8/8_quiz/lohi/lohi.cpp. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: Active checkers: 161/565
    at /Users/iustus/.vscode/extensions/jbenden.c-cpp-flylint-1.13.1/server/out/server.js:2:12689
    at Array.forEach (<anonymous>)
    at a.parseLines (/Users/iustus/.vscode/extensions/jbenden.c-cpp-flylint-1.13.1/server/out/server.js:2:12438)
    at a.lint (/Users/iustus/.vscode/extensions/jbenden.c-cpp-flylint-1.13.1/server/out/server.js:2:12341)
    at /Users/iustus/.vscode/extensions/jbenden.c-cpp-flylint-1.13.1/server/out/server.js:2:21825
    at Array.forEach (<anonymous>)
    at Function.B (/Users/iustus/.vscode/extensions/jbenden.c-cpp-flylint-1.13.1/server/out/server.js:2:21800)
```

**Comment by liaoya** [comment]
I solve the same issue with this setting.

**Comment by Joao-Peterson** [comment]
I could also could reproduce the error and the fix
