### ISSUE TITLE
FlyLint errors when opening a file directly

### ISSUE THREAD

**Issue by bensetterholm** [jbenden/vscode-c-cpp-flylint#3]
When I open just a file (without opening a directory first) in VS Code, I get the following error message:

    vscode-c-cpp-flylint: 'Path must be a string. Received undefined' while validating: /Users/bensett/Desktop/test.c. Please analyze the 'C/C++ FlyLint' Output console. ...

The Output console displays:

    Workspace root URI is not of the file scheme.
    Configuration changed. Re-configuring extension.
    TypeError: Path must be a string. Received undefined
        at assertPath (path.js:7:11)
        at Object.relative (path.js:1226:5)
        at validateTextDocument (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/server.js:89:31)
        at documents.onDidOpen (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/server.js:63:5)
        at CallbackList.invoke (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:114:39)
        at Emitter.fire (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/events.js:178:36)
        at connection.onDidOpenTextDocument (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/lib/main.js:151:29)
        at handleNotification (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:474:43)
        at processMessageQueue (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:246:17)
        at Immediate.<anonymous> (/Users/bensett/.vscode/extensions/jbenden.c-cpp-flylint-0.2.2/server/node_modules/vscode-languageserver/node_modules/vscode-jsonrpc/lib/main.js:233:13)

**Comment by jbenden** [comment]
A new release has been published that should resolve this bug report.

If the problem persists, please re-open.
