### ISSUE TITLE
ERROR: pc-lint    line could not be parsed.

### ISSUE THREAD

**Issue by suzukajiang** [jbenden/vscode-c-cpp-flylint#30]
When using PC-Lint, it is always hinting that the file cannot be parsed

Configuration changed. Re-configuring extension.
Performing lint scan of z:\sim-ue-json\test.c...
Completed lint scans...
Performing lint scan of z:\sim-ue-json\test.c...
Flexelint exited with status code 1
An exception occurred in Flexelint while parsing output for file z:\sim-ue-json\test.c stacktrace: Error: Line could not be parsed:          _
    at Flexelint.parseLine (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\flexelint.js:71:19)
    at lines.forEach.line (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:208:31)
    at Array.forEach (native)
    at Flexelint.parseLines (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:207:15)
    at Flexelint.lint (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:195:25)
    at lintersCopy.forEach.linter (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:104:39)
    at Array.forEach (native)
    at validateTextDocument (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:101:17)
    at validateAllTextDocuments (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:162:13)
    at Object.<anonymous> (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:286:5)
Completed lint scans...

**Comment by jbenden** [comment]
Please enable debugging verbose output, using the configuration setting:

`c-cpp-flylint.debug`: `true`

Then post the entire message output window log.

I am uncertain if it is actually erroring on the text `_` or if more follows that character.

Thanks,
-Joe

**Comment by suzukajiang** [comment]
the extension didn't find the include file. but I have config the include path in c_cpp_properties.json


Configuration changed. Re-configuring extension.
Performing lint scan of z:\sim-ue-json\test.c...
Completed lint scans...
Performing lint scan of z:\sim-ue-json\test.c...
executing:  C:\lint\lint-nt.exe -v -b -format=%f  %l %c  %t %n: %m z:\sim-ue-json\.flexelint.lnt -hsFr_1 -width(4096,0) -zero(400) z:\sim-ue-json\test.c
[ '         _',
  '#include <stdio.h>',
  'z:\\sim-ue-json\\test.c  1 9  Error 322: Unable to open include file \'stdio.h\'',
  '' ]
[ '' ]
Flexelint exited with status code 1
An exception occurred in Flexelint while parsing output for file z:\sim-ue-json\test.c stacktrace: Error: Line could not be parsed:          _
    at Flexelint.parseLine (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\flexelint.js:71:19)
    at lines.forEach.line (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:208:31)
    at Array.forEach (native)
    at Flexelint.parseLines (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:207:15)
    at Flexelint.lint (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\linters\linter.js:195:25)
    at lintersCopy.forEach.linter (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:104:39)
    at Array.forEach (native)
    at validateTextDocument (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:101:17)
    at validateAllTextDocuments (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:162:13)
    at Object.<anonymous> (C:\Users\j25321\.vscode\extensions\jbenden.c-cpp-flylint-0.5.4\server\server.js:286:5)
Completed lint scans...

**Comment by jbenden** [comment]
Hello,

You have to read Flexelint/PC-Lint manual. There **must** be a setting file called `.flexelintrc.lnt` in the project folder with all compiler, architecture, language options, and specific lint options for your project.

-Joe
