### ISSUE TITLE
CppCheck fails on globbed includePath

### ISSUE THREAD

**Issue by Wetmelon** [jbenden/vscode-c-cpp-flylint#53]
Extension fails to parse includePaths when globbing is used.  The includePath

"${workspaceRoot}/**"

is supported by VSCode and cpptools extension, but an error is thrown by flylint when this is used.  I'm using CppCheck in the backend.

Otherwise, the extension seems to work as advertised.

```
vscode-c-cpp-flylint: 'Line could not be parsed: (information) Couldn't find path given by -I 'c:\myProject\**\'' while validating: c:\myProject\Veh\_src\Veh.c. Please analyze the 'C/C++ FlyLint' Output console. Stacktrace: Error: Line could not be parsed: (information) Couldn't find path given by -I 'c:\myProject\**\'
    at lines.forEach.line (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\linters\linter.js:221:31)
    at Array.forEach (<anonymous>)
    at CppCheck.parseLines (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\linters\linter.js:205:15)
    at CppCheck.lint (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\linters\linter.js:195:21)
    at lintersCopy.forEach.linter (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\server.js:242:43)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\server.js:239:21)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Users\myUser\.vscode\extensions\jbenden.c-cpp-flylint-1.2.2\server\server.js:4:58)
```

**Comment by jbenden** [comment]
Hi! Thanks for the report.

This issue has been brought up before and discussed. At some point, VS Code introduced glob expressions to the mix. I simply pass all includes, as is, to the CLI tooling that does the actual linting work.

I am now willing to extend the extension to support globs. I am thinking of introducing a dependency on [`tiny-glob`](https://www.npmjs.com/package/tiny-glob) to handle the glob expansion.

Once again, thanks for the report! I'll keep this report posted with any updates!
-Joe
